/**
 * One-time phase-2 initialization (safe to re-run, idempotent):
 * 1. Check .env.local; generate and write ENCRYPTION_MASTER_KEY / ADMIN_TOKEN if missing
 * 2. Try connecting to Supabase and check whether the tables already exist
 * 3. If tables don't exist: prompt to run scripts/phase2-schema.sql in the Supabase console (REST doesn't support DDL — this is the officially recommended approach)
 * 4. Create the Storage bucket `uploads` (private) once available
 *
 * Usage: node scripts/setup-phase2.mjs
 * See PHASE2_SPEC.md sections 3.1 / 4.1 / 5.1 for the table structure.
 */
import { readFile, writeFile } from "node:fs/promises";
import { randomBytes } from "node:crypto";
import path from "node:path";
import { createClient } from "@supabase/supabase-js";

const ENV_PATH = path.resolve(process.cwd(), ".env.local");
const BUCKET = "uploads";

function log(message) {
  console.log(`[setup] ${message}`);
}

function parseEnv(content) {
  const map = new Map();
  for (const line of content.split(/\r?\n/)) {
    const match = line.match(/^([A-Z0-9_]+)=(.*)$/);
    if (match) map.set(match[1], match[2]);
  }
  return map;
}

function appendEnv(content, key, value) {
  const block = [
    "",
    "# --- Phase 2: config center (auto-generated by scripts/setup-phase2.mjs) ---",
    `${key}=${value}`,
    "",
  ].join("\n");
  return content.endsWith("\n") ? content + block.slice(1) : content + block;
}

async function ensureLocalSecrets() {
  let content;
  try {
    content = await readFile(ENV_PATH, "utf8");
  } catch {
    throw new Error("Could not find .env.local (this script needs to read the Supabase config from it)");
  }
  const env = parseEnv(content);
  const generated = [];

  if (!env.get("ENCRYPTION_MASTER_KEY")) {
    content = appendEnv(content, "ENCRYPTION_MASTER_KEY", randomBytes(32).toString("base64"));
    generated.push("ENCRYPTION_MASTER_KEY");
  } else {
    log("ENCRYPTION_MASTER_KEY already exists, skipping generation");
  }
  if (!env.get("ADMIN_TOKEN")) {
    content = appendEnv(content, "ADMIN_TOKEN", randomBytes(24).toString("base64url"));
    generated.push("ADMIN_TOKEN");
  } else {
    log("ADMIN_TOKEN already exists, skipping generation");
  }

  if (generated.length > 0) {
    await writeFile(ENV_PATH, content, "utf8");
    log(`Written to .env.local: ${generated.join(" / ")} (never share these values in any chat)`);
  }
  return parseEnv(content);
}

async function main() {
  await ensureLocalSecrets();
  const env = parseEnv(await readFile(ENV_PATH, "utf8"));
  const url = env.get("NEXT_PUBLIC_SUPABASE_URL");
  const serviceKey = env.get("SUPABASE_SERVICE_ROLE_KEY");
  if (!url || !serviceKey) {
    throw new Error("Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY, cannot connect to the database");
  }
  const client = createClient(url, serviceKey, { auth: { persistSession: false } });

  log("Checking database tables...");
  const missing = [];
  for (const table of ["app_config", "mail_accounts", "supabase_projects", "uploaded_documents"]) {
    const { error } = await client.from(table).select("*").limit(1);
    // When a table doesn't exist, Supabase's error text takes one of two forms: the old "does not exist", or the newer "Could not find the table ... in the schema cache"
    const notFound = error && /does not exist|could not find the table|schema cache/i.test(error.message);
    if (notFound) {
      missing.push(table);
    } else if (error) {
      log(`Check of ${table} returned: ${error.message} (continuing)`);
    }
  }

  if (missing.length > 0) {
    log(`The following tables don't exist yet: ${missing.join(" / ")}`);
    log("Supabase's API doesn't support creating tables (this is by official design). Please:");
    log("  1) Open the Supabase console -> SQL Editor");
    log("  2) Paste in the entire contents of scripts/phase2-schema.sql and run it");
    log("  3) Re-run this script");
    process.exitCode = 2;
    return;
  }
  log("All 4 tables already exist");

  const { data: buckets, error: listError } = await client.storage.listBuckets();
  if (listError) throw new Error(`Failed to list Storage buckets: ${listError.message}`);
  if (buckets.some((bucket) => bucket.name === BUCKET)) {
    log(`Storage bucket "${BUCKET}" already exists`);
  } else {
    const { error } = await client.storage.createBucket(BUCKET, { public: false });
    if (error) throw new Error(`Failed to create bucket: ${error.message}`);
    log(`Created private Storage bucket "${BUCKET}"`);
  }

  log("Done. After restarting the dev server (npm run dev): GET /features/config/api should return the config list.");
}

main().catch((err) => {
  console.error(`[setup] Failed: ${err.message}`);
  process.exitCode = 1;
});
