/**
 * Types and constants for the import feature (Phase 2 SPEC section 5).
 * This module is self-contained: the uploaded_documents table and the uploads Storage bucket are only read/written from here.
 */
import type { DocumentType } from "@/lib/shared/types";

// The single source of truth for the type is still lib/shared/types.ts; re-exported here for convenient use within this module
export type { DocumentType };

export const UPLOAD_BUCKET = "uploads";

// The two limits below are hardcoded to the SPEC defaults for now (storage.upload_max_file_mb=20 / upload_max_batch_mb=3);
// once the config system (config feature) is wired up, switch to reading app_config; this stage keeps behavior fixed and predictable.
export const MAX_FILE_BYTES = 20 * 1024 * 1024;
export const MAX_BATCH_BYTES = 3 * 1024 * 1024;
// Vercel's request body cap is about 4.5MB: base64 is ~33% larger than the original, so 3MB of original content is about 4MB; this leaves headroom and intercepts early
export const MAX_RAW_BODY_BYTES = 4_500_000;

export const UPLOAD_CONCURRENCY = 3;
export const DOCUMENT_PREVIEW_CHARS = 500;
export const DOCUMENT_LIST_DEFAULT_LIMIT = 20;
export const DOCUMENT_LIST_MAX_LIMIT = 200;
export const UPLOADED_BY = "admin";
export const MAX_FILE_NAME_LENGTH = 120;
// Max files per request (purely to guard against misuse: uploading is already token-protected; exceeding this returns a readable 400 suggesting batching)
export const MAX_BATCH_FILES = 50;

export const ALLOWED_EXTENSIONS = ["txt", "md", "pdf", "docx", "xlsx"] as const;
export type AllowedExtension = (typeof ALLOWED_EXTENSIONS)[number];

export const REVIEW_STATUSES = ["pending", "filed", "skipped"] as const;
export type ReviewStatus = (typeof REVIEW_STATUSES)[number];

// The runtime list of types (the single source of truth for the type is still lib/shared/types.ts;
// satisfies is used here to keep both in sync — if values are added/removed there, typecheck will
// error here)
export const DOCUMENT_TYPES = ["SI", "BL", "OTHER", "UNKNOWN"] as const satisfies readonly DocumentType[];
// Allowed manual-classification targets: an UNKNOWN document can only be changed to one of these three types
export const MANUAL_DOCUMENT_TYPES = ["SI", "BL", "OTHER"] as const;

export type ParseStatus = "ok" | "unreadable";

/** Upload request: each item in files is validated individually in processUploadedFile (a bad item doesn't 400 the whole batch) */
export interface UploadRequest {
  files: unknown[];
  batch_id?: string;
}

export type UploadItemStatus = "stored" | "duplicate" | "rejected";

export interface UploadItemResult {
  name: string;
  status: UploadItemStatus;
  /** Readable reason when rejected; an unreadable document also carries parse_error */
  reason?: string;
  id?: string;
  detected_type?: DocumentType;
  parse_status?: ParseStatus;
  parse_error?: string;
}

export interface UploadResponse {
  batch_id: string;
  items: UploadItemResult[];
}

export interface DocumentListQuery {
  review_status?: ReviewStatus;
  detected_type?: DocumentType;
  limit: number;
  offset: number;
}

export interface DocumentListItem {
  id: string;
  file_name: string;
  file_size: number;
  mime: string | null;
  file_hash: string;
  storage_path: string | null;
  parse_status: ParseStatus;
  parse_error: string | null;
  detected_type: DocumentType;
  review_status: ReviewStatus;
  uploaded_by: string | null;
  updated_at: string | null;
  /** The list only gives a preview of the first 500 characters, not the full text (full text is via the single-document detail endpoint) */
  extracted_text_preview: string | null;
}

export interface DocumentListResponse {
  total: number;
  limit: number;
  offset: number;
  items: DocumentListItem[];
}

export interface DocumentDetail extends DocumentListItem {
  extracted_text: string | null;
}

export interface ClassifyDocumentRequest {
  id: string;
  detected_type: DocumentType;
  /** Optional optimistic lock: returns 409 if it doesn't match the current updated_at in the database (SPEC section 6) */
  expected_updated_at?: string;
}

/** One row of the uploaded_documents table (column names match the database) */
export interface UploadedDocumentRow {
  id: string;
  file_name: string;
  file_size: number;
  mime: string | null;
  storage_path: string | null;
  file_hash: string;
  parse_status: ParseStatus;
  parse_error: string | null;
  extracted_text: string | null;
  detected_type: DocumentType;
  review_status: ReviewStatus;
  uploaded_by: string | null;
  updated_at: string | null;
}

/** Fields required for a newly inserted row (id / updated_at are generated by the database) */
export type NewDocumentRow = Omit<UploadedDocumentRow, "id" | "updated_at">;

export type UpdateClassificationResult =
  | { status: "ok"; row: UploadedDocumentRow }
  | { status: "conflict" }
  | { status: "not_found" };
